<a href="https://colab.research.google.com/github/MhizzyMacasieb/58013-Linear-Algebra/blob/main/Python%20Exercise%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[-0.4],[4.3],[-0.6]])
B = np.array([-0.2, 0.2, 1])
C = np.array([-0.2, 2.1, -1.5])

print(A,"\n")
print(B,"\n")
print(C,"\n")

[[-0.4]
 [ 4.3]
 [-0.6]] 

[-0.2  0.2  1. ] 

[-0.2  2.1 -1.5] 



**Addition**

In [2]:
print(np.add(B,C))
print(B+C)

[-0.4  2.3 -0.5]
[-0.4  2.3 -0.5]


**Subtraction**

In [3]:
print(np.subtract(C,B))
print(C-B)

[ 0.   1.9 -2.5]
[ 0.   1.9 -2.5]


**Scalar Product**

In [4]:
print(A*2)

[[-0.8]
 [ 8.6]
 [-1.2]]


**Dot Product**

In [5]:
print(np.dot(C,B),"\n")
print(np.dot(B,C),"\n")

-1.04 

-1.04 



**Multiply**

In [6]:
print(np.multiply(A,B),"\n")
print(np.multiply(A,C),"\n")

[[ 0.08 -0.08 -0.4 ]
 [-0.86  0.86  4.3 ]
 [ 0.12 -0.12 -0.6 ]] 

[[ 0.08 -0.84  0.6 ]
 [-0.86  9.03 -6.45]
 [ 0.12 -1.26  0.9 ]] 

