<a href="https://colab.research.google.com/github/MhizzyMacasieb/58013-Linear-Algebra/blob/main/Python%20Exercise%209.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [18]:
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

**Matrices A and B**

In [19]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
C = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(A)
print(B)
print(C,"\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]] 



**Associativite Property**

In [24]:
print("Associativite property")
result1 = np.dot(np.dot(A, B), C)
result2 = np.dot(A, np.dot(B, C))
print(result1)
print(result2,"\n")

Associativite property
[[ 324  396  468]
 [ 945 1152 1359]
 [1566 1908 2250]]
[[ 324  396  468]
 [ 945 1152 1359]
 [1566 1908 2250]] 



**Distributive Property**

In [22]:
print("Distributive property")
result3 = np.dot(A, B + C)
result4 = np.dot(A, B) + np.dot(A, C)
print(result3)
print(result4,"\n")

Distributive property
[[ 66  66  66]
 [165 165 165]
 [264 264 264]]
[[ 66  66  66]
 [165 165 165]
 [264 264 264]] 



**Multiplicative Identity Property**

In [23]:
print("Multiplicative identity property")
identity_matrix = np.identity(3)
result5 = np.dot(A, identity_matrix)
result6 = np.dot(identity_matrix, A)
print(result5)
print(result6,"\n")

Multiplicative identity property
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 



**Dimension Property**

In [25]:
print("Dimension Property")
k = 2
result7 = np.dot(k * A, B)
result8 = k * np.dot(A, B)
print(result7)
print(result8,"\n")

Dimension Property
[[ 60  48  36]
 [168 138 108]
 [276 228 180]]
[[ 60  48  36]
 [168 138 108]
 [276 228 180]] 



**Commutative Property**

In [26]:
print("Commutative property")
result9 = np.dot(A, B)
result10 = np.dot(B, A)
print(result9)
print(result10,"\n")

Commutative property
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]] 



**Zero Matrix**

In [27]:
print("Zero Matrix")
zero_matrix = np.zeros((3, 3))
result11 = np.dot(A, zero_matrix)
result12 = np.dot(zero_matrix, A)
print(result11)
print(result12,"\n")

Zero Matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

