<a href="https://colab.research.google.com/github/MhizzyMacasieb/58013-Linear-Algebra/blob/main/Vector%2C_Spaces_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

A = np.array([4,3])
B = np.array([2, -5])

print('Vector A is [4 3]')
print('Vector B is [2 -5]')

Vector A is [4 3]
Vector B is [2 -5]


**Line, Dimension, Size**

In [6]:
import numpy as np

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

print(ball1)
print(ball2)

ball = np.shape(ball1)
balls = np.shape(ball2)

z = ball+balls
print(z)

y = np.ndim(ball1)
print(y)

[1 2 3]
[ 0  1 -1]
(3, 3)
1


**Operation of Vectors**

In [18]:
#Addition

A = np.array([4,3])
B = np.array([2,-5])
R = np.add(A,B)
print(R)

[ 6 -2]


In [19]:
#Subtraction

R1 = np.subtract(A,B)
print(R1)
R2 = np.subtract(B,A)
print(R2)

[2 8]
[-2 -8]


In [20]:
#Scalar Product
S = np.array([2])
V = S*A
print(V)

[8 6]


In [31]:
#Property of Matrix
#Identity of Matrix
c = np.eye(3,3)
print(c)

#Zero Matrix
d = np.zeros([5,5])
print(d)

#Full Matrix
e = np.full((3,3),7)
print(e)

#Transpose Matrix
f = np.transpose(A)
print(f)

#Null Matrix
n = np.empty(0)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[4 3]
[]
